-- Up Migration
-- ============================================================
-- 003 — User management: users, roles, permissions (RBAC)
-- Run after migration-002-features.sql
-- ============================================================

CREATE TABLE permissions (
  code        text PRIMARY KEY,             -- 'product.edit'
  description text NOT NULL
);

CREATE TABLE roles (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  code        text NOT NULL UNIQUE,         -- 'editor'
  name        text NOT NULL,
  is_system   boolean NOT NULL DEFAULT false,  -- system roles can't be deleted
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE role_permissions (
  role_id         uuid NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
  permission_code text NOT NULL REFERENCES permissions(code) ON DELETE CASCADE,
  PRIMARY KEY (role_id, permission_code)
);

CREATE TABLE users (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email         text NOT NULL UNIQUE,
  name          text NOT NULL,
  password_hash text NOT NULL,              -- scrypt: salt:hash
  active        boolean NOT NULL DEFAULT true,
  last_login_at timestamptz,
  created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE user_roles (
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role_id uuid NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, role_id)
);

-- Attribute history & reviews now reference real users (kept as text for
-- backward compatibility; new writes should store the user's email).

-- ---------- Seed permissions ----------
INSERT INTO permissions (code, description) VALUES
  ('product.view',    'View products and assets'),
  ('product.edit',    'Create and edit products, variants, assets'),
  ('product.publish', 'Publish, archive, set publish windows'),
  ('review.approve',  'Approve or reject products in review'),
  ('model.manage',    'Manage product types and attribute definitions'),
  ('import.run',      'Run CSV imports and exports'),
  ('settings.manage', 'Manage webhooks, channels, share links'),
  ('user.manage',     'Manage users and roles');

-- ---------- Seed roles ----------
INSERT INTO roles (code, name, is_system) VALUES
  ('admin',           'Administrator',   true),
  ('catalog_manager', 'Catalog Manager', true),
  ('editor',          'Editor',          true),
  ('reviewer',        'Reviewer',        true),
  ('viewer',          'Viewer',          true);

INSERT INTO role_permissions (role_id, permission_code)
SELECT r.id, p.code FROM roles r JOIN permissions p ON CASE r.code
  WHEN 'admin'           THEN true
  WHEN 'catalog_manager' THEN p.code IN ('product.view','product.edit','product.publish','review.approve','import.run','settings.manage','model.manage')
  WHEN 'editor'          THEN p.code IN ('product.view','product.edit')
  WHEN 'reviewer'        THEN p.code IN ('product.view','review.approve')
  WHEN 'viewer'          THEN p.code IN ('product.view')
END;

-- ---------- Bootstrap admin (password: change-me — replace immediately) ----------
-- Hash generated by src/lib/auth.ts hashPassword('change-me'); placeholder here,
-- real deployments should create the admin via `npm run create-admin`.
